os: linux

language:
  go

services:
  - docker
  
script:
- go test -v ./...
- CGO_ENABLED=0 go build -o demo
- echo "$REGISTRY_PASSWORD" | docker login --username $REGISTRY_USER --password-stdin
- docker build -f Dockerfile -t lukashubl/demo:latest ./
- GIT_SHA="$(git rev-parse --short HEAD)"
- docker tag lukashubl/demo:latest lukashubl/demo:$GIT_SHA
- docker push lukashubl/demo:latest
- docker push lukashubl/demo:$GIT_SHA